replicaCount: 1
image:
  repository: gitlab.dev.ifs.hsr.ch:45023/epj/2020/coastline/application/server
  tag: "1-0-0"
  pull_secret: gitlab-registry-coastline-application
secret:
  coastline_database_uri: U2VydmVyPTEyNy4wLjAuMTtQb3J0PTcwMDA7RGF0YWJhc2U9Y29hc3RsaW5lO1VzZXIgSWQ9cG9zdGdyZXM7UGFzc3dvcmQ9bXlzZWNyZXRwYXNzd29yZDs=
config:
  database_migrations: manuel
  allowed_hosts: "*"
  allowed_origin: coastline.app
  auth0_domain: coastline-app.eu.auth0.com
  auth0_audience: http://api.coastline.app
service:
  port: 80
ingress:
  host: api.coastline.app
resources:
  requests:
    cpu: "50m"
  limits:
    cpu: "50m"
