// <auto-generated />
using System;
using CoastlineServer.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CoastlineServer.DAL.Migrations
{
    [DbContext(typeof(CoastlineContext))]
    [Migration("20200331124122_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CoastlineServer.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Biography")
                        .HasColumnType("VARCHAR(140)");

                    b.Property<string>("DegreeProgram")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("LastName")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("StartDate")
                        .HasColumnType("VARCHAR(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Biography = "Start HS2018",
                            DegreeProgram = "Informatik",
                            Email = "david.luthiger@hsr.ch",
                            FirstName = "David",
                            LastName = "Luthiger",
                            StartDate = "HS2018"
                        },
                        new
                        {
                            Id = -2,
                            Biography = "Start HS2018",
                            DegreeProgram = "Informatik",
                            Email = "fabian.germann@hsr.ch",
                            FirstName = "Fabian",
                            LastName = "Germann",
                            StartDate = "HS2018"
                        },
                        new
                        {
                            Id = -3,
                            Biography = "Start HS2018",
                            DegreeProgram = "Informatik",
                            Email = "eliane.schmidli@hsr.ch",
                            FirstName = "Eliane",
                            LastName = "Schmidli",
                            StartDate = "HS2018"
                        },
                        new
                        {
                            Id = -4,
                            Biography = "Start HS2018",
                            DegreeProgram = "Informatik",
                            Email = "yves.boillat@hsr.ch",
                            FirstName = "Yves",
                            LastName = "Boillat",
                            StartDate = "HS2018"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
