apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
data:
  database-migrations: {{ .Values.config.database_migrations }}
  allowed-hosts: "{{ .Values.config.allowed_hosts }}"
  allowed-origin: "{{ .Values.config.allowed_origin }}"
  auth0-domain: "{{ .Values.config.auth0_domain }}"
  auth0-audience: "{{ .Values.config.auth0_audience }}"
