version: '2.0'
services:
  web:
    build:
      context: .
      dockerfile: prod.dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - AllowedHosts=*
      - AllowedOrigin=http://localhost:8080
      - DatabaseMigrations=automatic
      - ConnectionStringCoastline=Server=db;Port=5432;Database=coastline;User Id=postgres;Password=mysecretpassword;
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword