version: '2.0'
services:
  api:
    build:
      context: .
      dockerfile: prod.dockerfile
    image: coastline-server
    container_name: cl-api
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - AllowedHosts=*
      - AllowedOrigin=http://localhost:8080
      - DatabaseMigrations=automatic
      - ConnectionStringCoastline=Server=db;Port=5432;Database=coastline;User Id=postgres;Password=mysecretpassword;
      - Auth0Domain=dev-coastline.eu.auth0.com
      - Auth0Audience=http://localhost:5000
  db:
    image: postgres
    container_name: cl-db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword