replicaCount: 1
image:
  repository: gitlab.dev.ifs.hsr.ch:45023/epj/2020/coastline/ci-cd-setup/client
  tag: "1-0-0"
  pull_secret: gitlab-registry-ci-cd-test
config:
  coastline_api_uri: "https://api.coastline.app"
service:
  port: 80
ingress:
  host: coastline.app
