replicaCount: 1
image:
  repository: gitlab.dev.ifs.hsr.ch:45023/epj/2020/coastline/application/client
  tag: "1-0-0"
  pull_secret: gitlab-registry-coastline-application
config:
  coastline_api_uri: "https://api.coastline.app"
  auth0_domain: "no_default"
  auth0_client_id: "no_default"
  auth0_audience: "no_default"
  auth0_redirect_uri: "no_default"
service:
  port: 80
ingress:
  host: coastline.app
resources:
  requests:
    cpu: "10m"
  limits:
    cpu: "10m"
